Add support for ignoring fields
capralifecycle/snapshot-test pull request #5
Opened 2021-02-01 12:53 UTC by staklau

2021-02-01 13:15 UTC, henrist requested changes
En observasjon her nå er at snapshots alltid vil endre seg når man kjører med `REGENERATE_SNAPSHOTS`. Usikker om vi ønsker oss et skille på å kun regenerere feilede snapshots. Det kan oppleves som mye å review hvis felter som i utgangspunktet ikke er relevant endrer seg hver gang man oppdaterer snapshots.

Når det gjelder testeksempelet her som bruker tid så lurer jeg på hvorvidt problemet her løses feil sted? Det høres ut som det som mangler er å styre klokken i en test. Hvilke andre use-caser har vi enn tid her?

2021-02-01 13:15 UTC, henrist commented on src/main/kotlin/no/liflig/snapshot/Snapshot.kt
> +      JSONAssert.assertEquals(
Dette endrer oppførsel på metoden fra å være exactly string-lik til å parse f.eks. whitespace. Det er derfor ikke en "exactly match" som beskrevet i KDoc.

`verifyStringSnapshot` burde ikke vite noen ting om JSON her. Det innføres nå en leaky abstraction

2021-02-01 13:15 UTC, henrist commented on src/main/kotlin/no/liflig/snapshot/Snapshot.kt
> +  ignoredValues: List<String>? = null
Er dette navngitt galt? Det er vel ikke spesifikke _verdier_ som ignoreres? Det er ulike JSON Paths (?)?

KDoc må oppdateres

2021-02-01 13:15 UTC, henrist commented on src/main/kotlin/no/liflig/snapshot/Snapshot.kt
> +            .map { Customization(it) { o1: Any?, o2: Any? -> o2 != null } }
Du får sikkert warning ved bygg på `o1` her? Hva representerer `o1` og `o2`? Disse bør gis et forståelig alias. `o1` bør nok være `_` hvis det ikkebrukes.

2021-02-01 14:28 UTC, staklau commented
> En observasjon her nå er at snapshots alltid vil endre seg når man kjører med `REGENERATE_SNAPSHOTS`. Usikker om vi ønsker oss et skille på å kun regenerere feilede snapshots. Det kan oppleves som mye å review hvis felter som i utgangspunktet ikke er relevant endrer seg hver gang man oppdaterer snapshots.
> 
> Når det gjelder testeksempelet her som bruker tid så lurer jeg på hvorvidt problemet her løses feil sted? Det høres ut som det som mangler er å styre klokken i en test. Hvilke andre use-caser har vi enn tid her?

Use caset vårt er at vi skal kjøre tester på endepunktene i CL for å teste flyten i applikasjonen, f.eks. `opprette studieprogram -> opprette fagmappe i studieprogram -> opprette artikkel i fagmappe`. Vi skal også legge til snapshot-tester for responsen fra endepunktene, og da har vi ikke kontroll over klokkeslett og IDer til objektene som opprettes.

Tenkte det var lurt å legge det til i dette biblioteket, men kanskje ikke? Anders har også lagt til lignende tester i `europris-product` der han har behov for å ignorere felter, så da kunne han tatt i bruk dette biblioteket der også.

2021-02-01 15:03 UTC, henrist commented
> Use caset vårt er at vi skal kjøre tester på endepunktene i CL for å teste flyten i applikasjonen, f.eks. `opprette studieprogram -> opprette fagmappe i studieprogram -> opprette artikkel i fagmappe`. Vi skal også legge til snapshot-tester for responsen fra endepunktene, og da har vi ikke kontroll over klokkeslett og IDer til objektene som opprettes.

Aha! Gir mening :+1: 

> Tenkte det var lurt å legge det til i dette biblioteket, men kanskje ikke? Anders har også lagt til lignende tester i `europris-product` der han har behov for å ignorere felter, så da kunne han tatt i bruk dette biblioteket der også.

Helt kurant å legge inn her - bare pass på å ivareta abstraksjonene (f.eks. json vs string) og at ting er korrekt dokumentert

2021-02-02 08:11 UTC, merged

2021-02-02 12:32 UTC, henrist commented
Ble bra!

Merk at `assertJsonSnapshot` nok hører bedre hjemme i `Json.kt` - siden den filen holder på JSON-spesifikke detaljer.

2021-02-02 12:57 UTC, henrist commented
Forøvrig foretrekk å bruk "squash and merge" for å unngå å dra med masse ikke-relevant historikk inn i master